#!/bin/sh

set -e # using the options command to abort script at first error
echo
echo "PRE-COMMIT"

EMAIL=$(git config user.email)

if [[ $EMAIL != *"@coventry.ac.uk" ]]; then
  echo "  invalid config settings"
  echo "  Your registered email is currently '$EMAIL'"
  echo "  please run the following git commands:"
  echo "    $ git config user.email xxx@coventry.ac.uk"
  echo "    $ git config user.name 'zzz'"
  echo "  where 'xxx' is your university username"
  echo "  and 'zzz' is your name as it appears on your university ID badge"
  echo
  exit 1
fi

branch="$(git rev-parse --abbrev-ref HEAD)"

echo "  you are trying to commit to the '$branch' branch"

if [ "$branch" = "master" ]; then
  echo "    you can't commit directly to the master branch"
  echo "    create a local feature branch first"
  exit 1
fi

# check for valid branch name:

# valid_branch_regex="^iss\d{3}\/[a-z\-]+$"

# if [[ ! $local_branch =~ $valid_branch_regex ]]
# then
#     echo "invalid branch name"
#     echo "  format is: 'iss000/issue-name'"
#     echo "  replacing '000' with the issue number and 'issue-name' with the issue name"
#     echo "  only lower-case letters and replace spaces in the issue name with dashes"
#     echo "  rename your branch and try again"
#     exit 1
# fi

./node_modules/.bin/eslint .
